### ISSUE TITLE
Exception: Error launching CUDA compiler: 256

### ISSUE THREAD

**Issue by Amireng72** [Amireng72/OpenMM#1]
Hello everyone,

I am trying to run an OpenMM input, created by Charm-GUI, on HPC. I tried both OpenMM 7.4.2 and OpenMM 7.6.0, but in both of them I got this error: Exception: Error launching CUDA compiler: 256 (which I put all the error below). 

I have also tried running this OpenMM input on OpenMM 7.5 beta, which is mentioned as a solution for this problem in issue #2779, but my problem still doesn't resolve. 

I would really appreciate if you help me out with this problem.

I put my input file in link blow:
https://texastechuniversity-my.sharepoint.com/:f:/g/personal/abakhtii_ttu_edu/EuvhMqW9krZHlDlnLnfxfnYBJ3uwZvB58GibA1VY5jEnKg?e=q8tMhP

Here is error that I get:

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x559d2c285640_18300.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x559d2c285640_18300.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x559d2c285640_18300.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x557844bd0310_18358.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x557844bd0310_18358.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x557844bd0310_18358.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x560fb5efc940_18416.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x560fb5efc940_18416.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x560fb5efc940_18416.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x5603b963bb70_18604.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x5603b963bb70_18604.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x5603b963bb70_18604.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x55980974dc70_18679.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x55980974dc70_18679.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x55980974dc70_18679.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x55b32d8b0540_18737.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x55b32d8b0540_18737.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x55b32d8b0540_18737.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x5594bd2baf30_18812.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x5594bd2baf30_18812.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x5594bd2baf30_18812.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x56397537b000_18867.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x56397537b000_18867.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x56397537b000_18867.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x562a9ac0f000_18923.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x562a9ac0f000_18923.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x562a9ac0f000_18923.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x55b211dbb000_18979.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x55b211dbb000_18979.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x55b211dbb000_18979.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x557ee0594000_19092.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x557ee0594000_19092.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x557ee0594000_19092.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x556f55856f00_19152.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x556f55856f00_19152.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x556f55856f00_19152.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x5649835437f0_19223.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x5649835437f0_19223.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x5649835437f0_19223.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x56469c708000_19298.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x56469c708000_19298.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x56469c708000_19298.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x56348e4f4000_19412.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x56348e4f4000_19412.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x56348e4f4000_19412.cu".

Traceback (most recent call last):
  File "openmm_run.py", line 106, in <module>
    simulation = Simulation(top.topology, system, integrator, platform, prop)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/home/abakhtii/anaconda3/envs/py36/lib/python3.6/site-packages/simtk/openmm/openmm.py", line 18608, in __init__
    this = _openmm.new_Context(*args)
Exception: Error launching CUDA compiler: 256
/tmp/openmmTempKernel0x55d65e2ef000_19468.cu(1002): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

/tmp/openmmTempKernel0x55d65e2ef000_19468.cu(1003): error: calling a constexpr __host__ function("fmin") from a __global__ function("computeBondedForces") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

2 errors detected in the compilation of "/tmp/openmmTempKernel0x55d65e2ef000_19468.cu".

**Comment by Amireng72** [comment]
I fixed the error. the new version of OpenMM 7 was not compatible with Cuda version that has been using in HPCC. I fixed the problem by using opeMM 7.5.1 (version:py36h08e60dd_1) and also I downgrade my cudaTool
